database:
  host: "127.0.0.1"
  port: 5432
  dbname: "wavenet_db"
  username: "postgres"
  password: "2310Asadbek"
  log_level: "DEBUG"
  log_file: "db.json"
http_server:
  host: "127.0.0.1"
  port: 8000
  log_level: "DEBUG"
  log_file: "api.json"
smtp_server:
  host: "127.0.0.1"
  port: 2525
  log_level: "DEBUG"
  log_file: "smtp.json"
