import type { Metadata } from "next";
import "@/style/globals.css";

import LandingHeader from "@/features/LandingHeader/ui/LandingHeader";

export const metadata: Metadata = {
  title: "WaveNet - Social Media Platform",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">

      <body className="min-h-full flex flex-col"> <LandingHeader/> {children}</body>
    </html>
  );
}
