import type { Metadata } from "next";
import "@/style/globals.css";

import LandingHeader from "@/features/LandingHeader/ui/LandingHeader";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "WaveNet - Social Media Platform",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("h-full antialiased", "font-sans", geist.variable)}>

      <body className="min-h-full flex flex-col"> <LandingHeader/> {children}</body>
    </html>
  );
}
